### ISSUE TITLE
Changing path

### ISSUE THREAD

**Issue by Sparklight77** [CallMeSoumya2063/draco-injector-script#1]
Hi bro, i got a suggestion, change path from `sdcard/Downloads` to `/sdcard/injector` and tell in your tutorial to first create a folder named injector and then place Minecraft and injector.sh in it, this will make it more organised.

**Comment by CallMeSoumya2063** [comment]
I don't see how it's useful

**Comment by Sparklight77** [comment]
Huh whatever
I am saying it would be organised
